AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures: ['x86_64']
    Environment:
      Variables:
        NODE_OPTIONS: '--enable-source-maps'
    EphemeralStorage:
      Size: 512
  Api:
    OpenApiVersion: '2.0'
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
      MaxAge: 600

Resources:
  CoreLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nest-core-layer
      Description: Core dependencies for Nest.js application
      ContentUri: layer/core
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain
  DatabaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nest-database-layer
      Description: Database dependencies for Nest.js application
      ContentUri: layer/database
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  AuthLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nest-auth-layer
      Description: Auth dependencies for Nest.js application
      ContentUri: layer/auth
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain
  AwsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nest-aws-layer
      Description: AWS dependencies for Nest.js application
      ContentUri: layer/aws
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nest-utils-layer
      Description: Utility dependencies for Nest.js application
      ContentUri: layer/utils
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes:
        - 'image/*'
        - 'multipart/form-data'
      Auth:
        DefaultAuthorizer: NONE

  NestjsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      SkipBuild: true
    Properties:
      Handler: lambda.handler
      CodeUri: ./dist
      MemorySize: 3008
      Timeout: 30
      Layers:
        - !Ref CoreLayer
        - !Ref DatabaseLayer
        - !Ref AuthLayer
        - !Ref AwsLayer
        - !Ref UtilsLayer
      Policies:
        - S3CrudPolicy:
            BucketName: aladdinagi-assets
        - VPCAccessPolicy: {}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref Api
            Auth:
              Authorizer: NONE
      AutoPublishAlias: live

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev'
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt NestjsFunction.Arn
