AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs18.x
    Architectures: ['x86_64']
    Environment:
      Variables:
        NODE_ENV: production
        NODE_OPTIONS: '--enable-source-maps'
    EphemeralStorage:
      Size: 512
  Api:
    OpenApiVersion: '2.0'
    Auth:
      ApiKeyRequired: true
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,X-Api-Key,Authorization'"
      AllowOrigin: "'*'"
      MaxAge: 600

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: web3-university-dependencies
      Description: Node modules for Web3 University Nest.js application
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes:
        - 'image/*'
        - 'multipart/form-data'

  NestFunction:
    Type: AWS::Serverless::Function
    Metadata:
      SkipBuild: true
    Properties:
      Handler: lambda.handler
      CodeUri: ./dist
      MemorySize: 3008
      Timeout: 30
      Layers:
        - !Ref NodeModulesLayer
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: '*'
            - Effect: Allow
              Action:
                - rds:*
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref Api
      AutoPublishAlias: live

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true
      Name: Web3UniversityApiKey

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref Api
          Stage: prod
      Description: Usage plan for Web3 University API
      UsagePlanName: Web3UniversityUsagePlan

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod'
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt NestFunction.Arn
  ApiKeyId:
    Description: API Key ID
    Value: !Ref ApiKey
